'use strict';

module.exports = {

  NAVBAR_TOGGLE: 'APPBAR',
  MAKE_FLASH: 'FLASH',
  FLASH_CLOSE: 'FLASHCLOSE',
  TX_UPDATE: 'TXUPDATE',
  NAVBAR_UPDATE: 'NAVUPDATE',
  AUTHENTICATED: 'AUTHENTICATED',
  USER_STATE_CHANGE: 'USER'

};
